#=====================================================
#                     MISC                           #
#=====================================================
quarkus.http.port=${SERVER_PORT:8080}
quarkus.http.root-path=/demo-quarkus-trace
quarkus.log.decorate-stacktraces=false
#=====================================================
#                     Swagger                        #
#=====================================================
quarkus.smallrye-openapi.path=/demo-quarkus-trace/open-api
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/demo-quarkus-trace/swagger
quarkus.swagger-ui.theme=original
quarkus.swagger-ui.title=Demo-Quarkus-Trace
quarkus.swagger-ui.validator-url=none
#=====================================================
#                  Open Telemetry                    #
#=====================================================
quarkus.otel.enabled=true
quarkus.otel.traces.sampler=always_on
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.otel.propagators=tracecontext,baggage,xray
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
#=====================================================
#                  Authorization                     #
#=====================================================
#quarkus.security.auth.basic=false