export enum TabEnumType {
    HOME = "HOME",
    ENDPOINTS = "ENDPOINTS",
    SETTINGS = "SETTINGS",
    RUNNERS_PROFILES = "RUNNERS_PROFILES",
    RUNNERS = "RUNNERS",
    SCRIPTS = "SCRIPTS",
    PLANNER = "PLANNER",
    DOCUMENTATION = "DOCUMENTATION"
}